### ISSUE TITLE
Thread usage is crashing the app

### ISSUE THREAD

**Issue by brunoamuniz** [TotalCross/totalcross#70] opened 2020-07-13 14:03 UTC
## Describe the bug
I am getting the temperature and humidity using a DHT11, also updating the screen with a Thread and, after 1h, the app crash.

## To Reproduce
You should use this source code to reproduce. It takes a while running on the device to abort the application
https://github.com/TotalCross/HomeApplianceXML/tree/feature-dht-sensor

Also, connect on the raspberry with ssh and run a top command to track memory, it was increasing really fast.

## Expected behavior
The application should continue running with no problem.

## Devices:
raspberry pi 4

**Comment by flsobral** [comment] 2020-07-15 20:58
@brunoamuniz noticed that executing the application running the thread without using Runtime.exec did not cause memory problems and stopped crashing the application.

Upon further review, I noticed there might be some leakage from the streams obtained from the executing Process.
The leakage should be fixed by the PR #77, but more tests are required to check if it fixes the crash reported on this issue.

**Comment by flsobral** [comment] 2020-07-21 20:42
The crash was caused by the leakage of file descriptors. The excessive memory consumption appears to be a side effect from fork and, more importantly, does not reflect the actual physical memory consumption.

Fixed by #77

**Closed by flsobral** 2020-07-21 20:42 UTC
Labels: bug
