### ISSUE TITLE
Failure running app on IMX6s - Raizen

### ISSUE THREAD

**Issue by pedropaulolyra** [TotalCross/totalcross#263] opened 2021-01-11 17:26 UTC
## Issue Title
Raizen is trying to run a sample app that we sent on his device and got an error message. 

## Describe the bug
Message error: 

root@colibri-imx6:/raizen/totalcross# LD_LIBRARY_PATH=/usr/local/lib/sdl2 ./JBox
Testing video drivers...
SDL_VIDEODRIVER available: x11 wayland dummy
SDL_VIDEODRIVER usable   : x11
Segmentation fault (core dumped)

## To Reproduce

Project: 
https://github.com/TotalCross/KnowcodePrivateCases/tree/main/JBox.

## Devices:
- Colibri IMX6s single core / 256mb Ram.
- Toradex standard BSP. Also tested with BSP 2.8.7 Ångström LXDE Desktop Environment Image
 -TotalCross Version: [e.g. 6.1.1]

**Comment by teras** [comment] 2021-01-13 09:34
It looks like a duplicate of #259

**Closed** 2021-01-21 14:21 UTC
Labels: Linux ARM, bug, high
