### ISSUE TITLE
Unable to build TotalCross for Android using NDK 21

### ISSUE THREAD

**Issue by teras** [TotalCross/totalcross#165] opened 2020-10-15 13:03 UTC
## Describe the bug
When using the current NDK version 21.3.6528147 is it not possible to build TC master

## To Reproduce

1) Install Android SDK/Android Studio with recommended NDK (21.3.6528147)
2) Follow the [official TotalCross HOWTO](https://github.com/TotalCross/totalcross/wiki/How-to-build-TotalCross-VM-and-SDK-for-Android) to build Android VM
3) Build fails with this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.3.6528147, 21.3.6528147

```

## Expected behavior
TotalCross Android VM to build with current NDK. Only if there is some specific reason it shouldn't be possible.

## Devices:
 - OS: Mac OS
 - OS Version: 10.1
 - TotalCross Version: latest master version

**Comment by flsobral** [comment] 2020-11-30 14:27
This is caused by a bug on the Android Gradle Plugin, which expects to find the NDK 20.0.5594570 when none is specified, instead of using the latest available.
This is no longer an issue because the version of the NDK is now fixed on the build file.

**Closed by flsobral** 2020-11-30 14:27 UTC
Labels: bug
